fix(deps): update dependency effect to v3.14.14 (#6723)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [effect](https://redirect.github.com/Effect-TS/effect)
([source](https://redirect.github.com/Effect-TS/effect/tree/HEAD/packages/effect))
| [`3.14.12` ->
`3.14.14`](https://renovatebot.com/diffs/npm/effect/3.14.12/3.14.14) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/effect/3.14.14?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/effect/3.14.14?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/effect/3.14.12/3.14.14?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/effect/3.14.12/3.14.14?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>Effect-TS/effect (effect)</summary>

###
[`v3.14.14`](https://redirect.github.com/Effect-TS/effect/blob/HEAD/packages/effect/CHANGELOG.md#31414)

[Compare
Source](https://redirect.github.com/Effect-TS/effect/compare/effect@3.14.13...effect@3.14.14)

##### Patch Changes

- [#&#8203;4786](https://redirect.github.com/Effect-TS/effect/pull/4786)
[`6ed8d15`](https://redirect.github.com/Effect-TS/effect/commit/6ed8d1589beb181d30abc79afebdaabc1d101538)
Thanks [@&#8203;tim-smart](https://redirect.github.com/tim-smart)! -
drop use of performance.timeOrigin in clock

###
[`v3.14.13`](https://redirect.github.com/Effect-TS/effect/blob/HEAD/packages/effect/CHANGELOG.md#31413)

[Compare
Source](https://redirect.github.com/Effect-TS/effect/compare/effect@3.14.12...effect@3.14.13)

##### Patch Changes

- [#&#8203;4777](https://redirect.github.com/Effect-TS/effect/pull/4777)
[`ee77788`](https://redirect.github.com/Effect-TS/effect/commit/ee77788747e7ebbde6bfa88256cde49dbbad3608)
Thanks [@&#8203;gcanti](https://redirect.github.com/gcanti)! -
JSONSchema: apply `encodeOption` to each example and retain successful
results.

    **Example**

    ```ts
    import { JSONSchema, Schema } from "effect"

    const schema = Schema.Struct({
      a: Schema.propertySignature(Schema.BigInt).annotations({
        examples: [1n, 2n]
      })
    })

    console.log(JSON.stringify(JSONSchema.make(schema), null, 2))
    /*
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "$defs": {
        "BigInt": {
          "type": "string",
          "description": "a string to be decoded into a bigint"
        }
      },
      "type": "object",
      "required": [
        "a"
      ],
      "properties": {
        "a": {
          "$ref": "#/$defs/BigInt",
          "examples": [
            "1",
            "2"
          ]
        }
      },
      "additionalProperties": false
    }
    */
    ```

- [#&#8203;4701](https://redirect.github.com/Effect-TS/effect/pull/4701)
[`5fce6ba`](https://redirect.github.com/Effect-TS/effect/commit/5fce6ba19c3cc63cc0104e737e581ad989dedbf0)
Thanks [@&#8203;gcanti](https://redirect.github.com/gcanti)! - Fix
`JSONSchema.make` for `Exit` schemas.

    Before

    ```ts
    import { JSONSchema, Schema } from "effect"

    const schema = Schema.Exit({
      failure: Schema.String,
      success: Schema.Number,
      defect: Schema.Defect
    })

    console.log(JSON.stringify(JSONSchema.make(schema), null, 2))
    /*
    throws
    Error: Missing annotation
    at path: ["cause"]["left"]
details: Generating a JSON Schema for this schema requires an
"identifier" annotation
    schema (Suspend): CauseEncoded<string>
    */
    ```

    After

    ```ts
    import { JSONSchema, Schema } from "effect"

    const schema = Schema.Exit({
      failure: Schema.String,
      success: Schema.Number,
      defect: Schema.Defect
    })

    console.log(JSON.stringify(JSONSchema.make(schema), null, 2))
    /*
    Output:
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "$defs": {
        "CauseEncoded0": {
          "anyOf": [
            {
              "type": "object",
              "required": [
                "_tag"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Empty"
                  ]
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "_tag",
                "error"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Fail"
                  ]
                },
                "error": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "_tag",
                "defect"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Die"
                  ]
                },
                "defect": {
                  "$ref": "#/$defs/Defect"
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "_tag",
                "fiberId"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Interrupt"
                  ]
                },
                "fiberId": {
                  "$ref": "#/$defs/FiberIdEncoded"
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "_tag",
                "left",
                "right"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Sequential"
                  ]
                },
                "left": {
                  "$ref": "#/$defs/CauseEncoded0"
                },
                "right": {
                  "$ref": "#/$defs/CauseEncoded0"
                }
              },
              "additionalProperties": false
            },
            {
              "type": "object",
              "required": [
                "_tag",
                "left",
                "right"
              ],
              "properties": {
                "_tag": {
                  "type": "string",
                  "enum": [
                    "Parallel"
                  ]
                },
                "left": {
                  "$ref": "#/$defs/CauseEncoded0"
                },
                "right": {
                  "$ref": "#/$defs/CauseEncoded0"
                }
              },
              "additionalProperties": false
            }
          ],
          "title": "CauseEncoded<string>"
        },
        "Defect": {
          "$id": "/schemas/unknown",
          "title": "unknown"
        },
        "FiberIdEncoded": {
          "anyOf": [
            {
              "$ref": "#/$defs/FiberIdNoneEncoded"
            },
            {
              "$ref": "#/$defs/FiberIdRuntimeEncoded"
            },
            {
              "$ref": "#/$defs/FiberIdCompositeEncoded"
            }
          ]
        },
        "FiberIdNoneEncoded": {
          "type": "object",
          "required": [
            "_tag"
          ],
          "properties": {
            "_tag": {
              "type": "string",
              "enum": [
                "None"
              ]
            }
          },
          "additionalProperties": false
        },
        "FiberIdRuntimeEncoded": {
          "type": "object",
          "required": [
            "_tag",
            "id",
            "startTimeMillis"
          ],
          "properties": {
            "_tag": {
              "type": "string",
              "enum": [
                "Runtime"
              ]
            },
            "id": {
              "$ref": "#/$defs/Int"
            },
            "startTimeMillis": {
              "$ref": "#/$defs/Int"
            }
          },
          "additionalProperties": false
        },
        "Int": {
          "type": "integer",
          "description": "an integer",
          "title": "int"
        },
        "FiberIdCompositeEncoded": {
          "type": "object",
          "required": [
            "_tag",
            "left",
            "right"
          ],
          "properties": {
            "_tag": {
              "type": "string",
              "enum": [
                "Composite"
              ]
            },
            "left": {
              "$ref": "#/$defs/FiberIdEncoded"
            },
            "right": {
              "$ref": "#/$defs/FiberIdEncoded"
            }
          },
          "additionalProperties": false
        }
      },
      "anyOf": [
        {
          "type": "object",
          "required": [
            "_tag",
            "cause"
          ],
          "properties": {
            "_tag": {
              "type": "string",
              "enum": [
                "Failure"
              ]
            },
            "cause": {
              "$ref": "#/$defs/CauseEncoded0"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "_tag",
            "value"
          ],
          "properties": {
            "_tag": {
              "type": "string",
              "enum": [
                "Success"
              ]
            },
            "value": {
              "type": "number"
            }
          },
          "additionalProperties": false
        }
      ],
      "title": "ExitEncoded<number, string, Defect>"
    }
    */
    ```

- [#&#8203;4775](https://redirect.github.com/Effect-TS/effect/pull/4775)
[`570e45f`](https://redirect.github.com/Effect-TS/effect/commit/570e45f8cb936e42ec48f67f21bb2b7252f36c0c)
Thanks [@&#8203;gcanti](https://redirect.github.com/gcanti)! -
JSONSchema: preserve original key name when using `fromKey` followed by
`annotations`, closes
[#&#8203;4774](https://redirect.github.com/Effect-TS/effect/issues/4774).

    Before:

    ```ts
    import { JSONSchema, Schema } from "effect"

    const schema = Schema.Struct({
      a: Schema.propertySignature(Schema.String)
        .pipe(Schema.fromKey("b"))
        .annotations({})
    })

    console.log(JSON.stringify(JSONSchema.make(schema), null, 2))
    /*
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "a"
      ],
      "properties": {
        "a": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
    */
    ```

    After:

    ```ts
    import { JSONSchema, Schema } from "effect"

    const schema = Schema.Struct({
      a: Schema.propertySignature(Schema.String)
        .pipe(Schema.fromKey("b"))
        .annotations({})
    })

    console.log(JSON.stringify(JSONSchema.make(schema), null, 2))
    /*
    {
      "$schema": "http://json-schema.org/draft-07/schema#",
      "type": "object",
      "required": [
        "b"
      ],
      "properties": {
        "b": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
    */
    ```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update
again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/trpc/trpc).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4yNTcuMyIsInVwZGF0ZWRJblZlciI6IjM5LjI1Ny4zIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>