fix: Export required types for TypeScript workspaces (#5500)
* fix: Export required types for TypeScript workspaces

Exports additional types required to avoid Typescript compilation issues in TypeScript Workspace-based packages.

Fixes the following issue:
```
src/client/src/trpc.ts:8:14 - error TS2742: The inferred type of 'client' cannot be named without a reference to '../../../node_modules/@foobar/my-awesome-package/src/types'. This is likely not portable. A type annotation is necessary.

8 export const client = createTRPCClient<RootRouter>({
```